// Require Unit Definition class
const UnitDefinition = require("./src/definition");

/**
 * @const {UnitTypes}
 * @desc Enumeration of available Unit Types
 */
const UnitTypes = Object.freeze({
    Time: 0,
    Degree: 1,
    Pourcent: 2,
    Bit: 3,
    BitTime: 4,
    Byte: 5,
    ByteTime: 6,
    Octet: 7,
    OctetTime: 8,
    Count: 9,
    CountTime: 10,
    Hertz: 11,
    Watt: 12,
    WattTime: 13,
    Boolean: 14
});

module.exports = {
    Types: UnitTypes,
    MicroSecond: new UnitDefinition({ type: UnitTypes.Time, symbol: "μs", min: 0 }),
    NanoSecond: new UnitDefinition({ type: UnitTypes.Time, symbol: "ns", min: 0 }),
    MilliSecond: new UnitDefinition({ type: UnitTypes.Time, symbol: "ms", min: 0 }),
    Second: new UnitDefinition({ type: UnitTypes.Time, symbol: "s", min: 0 }),
    Minute: new UnitDefinition({ type: UnitTypes.Time, symbol: "m", min: 0 }),
    Hour: new UnitDefinition({ type: UnitTypes.Time, symbol: "h", min: 0 }),
    Day: new UnitDefinition({ type: UnitTypes.Time, symbol: "D", min: 0 }),
    Month: new UnitDefinition({ type: UnitTypes.Time, symbol: "M", min: 0 }),
    Year: new UnitDefinition({ type: UnitTypes.Time, symbol: "Y", min: 0 }),

    Celsius: new UnitDefinition({ type: UnitTypes.Degree, symbol: "C", min: -273.12 }),
    Fehrenheit: new UnitDefinition({ type: UnitTypes.Degree, symbol: "F", min: -459.67 }),
    Kelvin: new UnitDefinition({ type: UnitTypes.Degree, symbol: "K", min: 0 }),

    Pourcent: new UnitDefinition({ type: UnitTypes.Pourcent, symbol: "%", min: 0, max: 100 }),

    Bit: new UnitDefinition({ type: UnitTypes.Bit, symbol: "b", min: 0 }),
    KiloBit: new UnitDefinition({ type: UnitTypes.Bit, symbol: "kb", min: 0 }),
    MegaBit: new UnitDefinition({ type: UnitTypes.Bit, symbol: "Mb", min: 0 }),
    GigaBit: new UnitDefinition({ type: UnitTypes.Bit, symbol: "Gb", min: 0 }),
    TeraBit: new UnitDefinition({ type: UnitTypes.Bit, symbol: "Tb", min: 0 }),

    BitMicroSeconde: new UnitDefinition({ type: UnitTypes.BitTime, symbol: "b/μs", min: 0 }),
    BitNanoSeconde: new UnitDefinition({ type: UnitTypes.BitTime, symbol: "b/ns", min: 0 }),
    BitMilliSeconde: new UnitDefinition({ type: UnitTypes.BitTime, symbol: "b/ms", min: 0 }),
    BitSeconde: new UnitDefinition({ type: UnitTypes.BitTime, symbol: "b/s", min: 0 }),
    BitMinute: new UnitDefinition({ type: UnitTypes.BitTime, symbol: "b/m", min: 0 }),
    BitHour: new UnitDefinition({ type: UnitTypes.BitTime, symbol: "b/h", min: 0 }),
    BitDay: new UnitDefinition({ type: UnitTypes.BitTime, symbol: "b/D", min: 0 }),
    BitMonth: new UnitDefinition({ type: UnitTypes.BitTime, symbol: "b/M", min: 0 }),
    BitYear: new UnitDefinition({ type: UnitTypes.BitTime, symbol: "b/Y", min: 0 }),

    KiloBitMicroSeconde: new UnitDefinition({ type: UnitTypes.BitTime, symbol: "kb/μs", min: 0 }),
    KiloBitNanoSeconde: new UnitDefinition({ type: UnitTypes.BitTime, symbol: "kb/ns", min: 0 }),
    KiloBitMilliSeconde: new UnitDefinition({ type: UnitTypes.BitTime, symbol: "kb/ms", min: 0 }),
    KiloBitSeconde: new UnitDefinition({ type: UnitTypes.BitTime, symbol: "kb/s", min: 0 }),
    KiloBitMinute: new UnitDefinition({ type: UnitTypes.BitTime, symbol: "kb/m", min: 0 }),
    KiloBitHour: new UnitDefinition({ type: UnitTypes.BitTime, symbol: "kb/h", min: 0 }),
    KiloBitDay: new UnitDefinition({ type: UnitTypes.BitTime, symbol: "kb/D", min: 0 }),
    KiloBitMonth: new UnitDefinition({ type: UnitTypes.BitTime, symbol: "kb/M", min: 0 }),
    KiloBitYear: new UnitDefinition({ type: UnitTypes.BitTime, symbol: "kb/Y", min: 0 }),

    MegaBitMicroSeconde: new UnitDefinition({ type: UnitTypes.BitTime, symbol: "Mb/μs", min: 0 }),
    MegaBitNanoSeconde: new UnitDefinition({ type: UnitTypes.BitTime, symbol: "Mb/ns", min: 0 }),
    MegaBitMilliSeconde: new UnitDefinition({ type: UnitTypes.BitTime, symbol: "Mb/ms", min: 0 }),
    MegaBitSeconde: new UnitDefinition({ type: UnitTypes.BitTime, symbol: "Mb/s", min: 0 }),
    MegaBitMinute: new UnitDefinition({ type: UnitTypes.BitTime, symbol: "Mb/m", min: 0 }),
    MegaBitHour: new UnitDefinition({ type: UnitTypes.BitTime, symbol: "Mb/h", min: 0 }),
    MegaBitDay: new UnitDefinition({ type: UnitTypes.BitTime, symbol: "Mb/D", min: 0 }),
    MegaBitMonth: new UnitDefinition({ type: UnitTypes.BitTime, symbol: "Mb/M", min: 0 }),
    MegaBitYear: new UnitDefinition({ type: UnitTypes.BitTime, symbol: "Mb/Y", min: 0 }),

    GigaBitMicroSeconde: new UnitDefinition({ type: UnitTypes.BitTime, symbol: "Gb/μs", min: 0 }),
    GigaBitNanoSeconde: new UnitDefinition({ type: UnitTypes.BitTime, symbol: "Gb/ns", min: 0 }),
    GigaBitMilliSeconde: new UnitDefinition({ type: UnitTypes.BitTime, symbol: "Gb/ms", min: 0 }),
    GigaBitSeconde: new UnitDefinition({ type: UnitTypes.BitTime, symbol: "Gb/s", min: 0 }),
    GigaBitMinute: new UnitDefinition({ type: UnitTypes.BitTime, symbol: "Gb/m", min: 0 }),
    GigaBitHour: new UnitDefinition({ type: UnitTypes.BitTime, symbol: "Gb/h", min: 0 }),
    GigaBitDay: new UnitDefinition({ type: UnitTypes.BitTime, symbol: "Gb/D", min: 0 }),
    GigaBitMonth: new UnitDefinition({ type: UnitTypes.BitTime, symbol: "Gb/M", min: 0 }),
    GigaBitYear: new UnitDefinition({ type: UnitTypes.BitTime, symbol: "Gb/Y", min: 0 }),

    TeraBitMicroSeconde: new UnitDefinition({ type: UnitTypes.BitTime, symbol: "Tb/μs", min: 0 }),
    TeraBitNanoSeconde: new UnitDefinition({ type: UnitTypes.BitTime, symbol: "Tb/ns", min: 0 }),
    TeraBitMilliSeconde: new UnitDefinition({ type: UnitTypes.BitTime, symbol: "Tb/ms", min: 0 }),
    TeraBitSeconde: new UnitDefinition({ type: UnitTypes.BitTime, symbol: "Tb/s", min: 0 }),
    TeraBitMinute: new UnitDefinition({ type: UnitTypes.BitTime, symbol: "Tb/m", min: 0 }),
    TeraBitHour: new UnitDefinition({ type: UnitTypes.BitTime, symbol: "Tb/h", min: 0 }),
    TeraBitDay: new UnitDefinition({ type: UnitTypes.BitTime, symbol: "Tb/D", min: 0 }),
    TeraBitMonth: new UnitDefinition({ type: UnitTypes.BitTime, symbol: "Tb/M", min: 0 }),
    TeraBitYear: new UnitDefinition({ type: UnitTypes.BitTime, symbol: "Tb/Y", min: 0 }),

    Byte: new UnitDefinition({ type: UnitTypes.Byte, symbol: "B", min: 0 }),
    KiloByte: new UnitDefinition({ type: UnitTypes.Byte, symbol: "kB", min: 0 }),
    MegaByte: new UnitDefinition({ type: UnitTypes.Byte, symbol: "MB", min: 0 }),
    GigaByte: new UnitDefinition({ type: UnitTypes.Byte, symbol: "GB", min: 0 }),
    TeraByte: new UnitDefinition({ type: UnitTypes.Byte, symbol: "TB", min: 0 }),

    ByteMicroSeconde: new UnitDefinition({ type: UnitTypes.ByteTime, symbol: "B/μs", min: 0 }),
    ByteNanoSeconde: new UnitDefinition({ type: UnitTypes.ByteTime, symbol: "B/ns", min: 0 }),
    ByteMilliSeconde: new UnitDefinition({ type: UnitTypes.ByteTime, symbol: "B/ms", min: 0 }),
    ByteSeconde: new UnitDefinition({ type: UnitTypes.ByteTime, symbol: "B/s", min: 0 }),
    ByteMinute: new UnitDefinition({ type: UnitTypes.ByteTime, symbol: "B/m", min: 0 }),
    ByteHour: new UnitDefinition({ type: UnitTypes.ByteTime, symbol: "B/h", min: 0 }),
    ByteDay: new UnitDefinition({ type: UnitTypes.ByteTime, symbol: "B/D", min: 0 }),
    ByteMonth: new UnitDefinition({ type: UnitTypes.ByteTime, symbol: "B/M", min: 0 }),
    ByteYear: new UnitDefinition({ type: UnitTypes.ByteTime, symbol: "B/Y", min: 0 }),

    KiloByteMicroSeconde: new UnitDefinition({ type: UnitTypes.ByteTime, symbol: "kB/μs", min: 0 }),
    KiloByteNanoSeconde: new UnitDefinition({ type: UnitTypes.ByteTime, symbol: "kB/ns", min: 0 }),
    KiloByteMilliSeconde: new UnitDefinition({ type: UnitTypes.ByteTime, symbol: "kB/ms", min: 0 }),
    KiloByteSeconde: new UnitDefinition({ type: UnitTypes.ByteTime, symbol: "kB/s", min: 0 }),
    KiloByteMinute: new UnitDefinition({ type: UnitTypes.ByteTime, symbol: "kB/m", min: 0 }),
    KiloByteHour: new UnitDefinition({ type: UnitTypes.ByteTime, symbol: "kB/h", min: 0 }),
    KiloByteDay: new UnitDefinition({ type: UnitTypes.ByteTime, symbol: "kB/D", min: 0 }),
    KiloByteMonth: new UnitDefinition({ type: UnitTypes.ByteTime, symbol: "kB/M", min: 0 }),
    KiloByteYear: new UnitDefinition({ type: UnitTypes.ByteTime, symbol: "kB/Y", min: 0 }),

    MegaByteMicroSeconde: new UnitDefinition({ type: UnitTypes.ByteTime, symbol: "MB/μs", min: 0 }),
    MegaByteNanoSeconde: new UnitDefinition({ type: UnitTypes.ByteTime, symbol: "MB/ns", min: 0 }),
    MegaByteMilliSeconde: new UnitDefinition({ type: UnitTypes.ByteTime, symbol: "MB/ms", min: 0 }),
    MegaByteSeconde: new UnitDefinition({ type: UnitTypes.ByteTime, symbol: "MB/s", min: 0 }),
    MegaByteMinute: new UnitDefinition({ type: UnitTypes.ByteTime, symbol: "MB/m", min: 0 }),
    MegaByteHour: new UnitDefinition({ type: UnitTypes.ByteTime, symbol: "MB/h", min: 0 }),
    MegaByteDay: new UnitDefinition({ type: UnitTypes.ByteTime, symbol: "MB/D", min: 0 }),
    MegaByteMonth: new UnitDefinition({ type: UnitTypes.ByteTime, symbol: "MB/M", min: 0 }),
    MegaByteYear: new UnitDefinition({ type: UnitTypes.ByteTime, symbol: "MB/Y", min: 0 }),

    GigaByteMicroSeconde: new UnitDefinition({ type: UnitTypes.ByteTime, symbol: "GB/μs", min: 0 }),
    GigaByteNanoSeconde: new UnitDefinition({ type: UnitTypes.ByteTime, symbol: "GB/ns", min: 0 }),
    GigaByteMilliSeconde: new UnitDefinition({ type: UnitTypes.ByteTime, symbol: "GB/ms", min: 0 }),
    GigaByteSeconde: new UnitDefinition({ type: UnitTypes.ByteTime, symbol: "GB/s", min: 0 }),
    GigaByteMinute: new UnitDefinition({ type: UnitTypes.ByteTime, symbol: "GB/m", min: 0 }),
    GigaByteHour: new UnitDefinition({ type: UnitTypes.ByteTime, symbol: "GB/h", min: 0 }),
    GigaByteDay: new UnitDefinition({ type: UnitTypes.ByteTime, symbol: "GB/D", min: 0 }),
    GigaByteMonth: new UnitDefinition({ type: UnitTypes.ByteTime, symbol: "GB/M", min: 0 }),
    GigaByteYear: new UnitDefinition({ type: UnitTypes.ByteTime, symbol: "GB/Y", min: 0 }),

    TeraByteMicroSeconde: new UnitDefinition({ type: UnitTypes.ByteTime, symbol: "TB/μs", min: 0 }),
    TeraByteNanoSeconde: new UnitDefinition({ type: UnitTypes.ByteTime, symbol: "TB/ns", min: 0 }),
    TeraByteMilliSeconde: new UnitDefinition({ type: UnitTypes.ByteTime, symbol: "TB/ms", min: 0 }),
    TeraByteSeconde: new UnitDefinition({ type: UnitTypes.ByteTime, symbol: "TB/s", min: 0 }),
    TeraByteMinute: new UnitDefinition({ type: UnitTypes.ByteTime, symbol: "TB/m", min: 0 }),
    TeraByteHour: new UnitDefinition({ type: UnitTypes.ByteTime, symbol: "TB/h", min: 0 }),
    TeraByteDay: new UnitDefinition({ type: UnitTypes.ByteTime, symbol: "TB/D", min: 0 }),
    TeraByteMonth: new UnitDefinition({ type: UnitTypes.ByteTime, symbol: "TB/M", min: 0 }),
    TeraByteYear: new UnitDefinition({ type: UnitTypes.ByteTime, symbol: "TB/Y", min: 0 }),

    Octet: new UnitDefinition({ type: UnitTypes.Octet, symbol: "o", min: 0 }),
    KiloOctet: new UnitDefinition({ type: UnitTypes.Octet, symbol: "ko", min: 0 }),
    MegaOctet: new UnitDefinition({ type: UnitTypes.Octet, symbol: "Mo", min: 0 }),
    GigaOctet: new UnitDefinition({ type: UnitTypes.Octet, symbol: "Go", min: 0 }),
    TeraOctet: new UnitDefinition({ type: UnitTypes.Octet, symbol: "To", min: 0 }),

    OctetMicroSeconde: new UnitDefinition({ type: UnitTypes.OctetTime, symbol: "o/μs", min: 0 }),
    OctetNanoSeconde: new UnitDefinition({ type: UnitTypes.OctetTime, symbol: "o/ns", min: 0 }),
    OctetMilliSeconde: new UnitDefinition({ type: UnitTypes.OctetTime, symbol: "o/ms", min: 0 }),
    OctetSeconde: new UnitDefinition({ type: UnitTypes.OctetTime, symbol: "o/s", min: 0 }),
    OctetMinute: new UnitDefinition({ type: UnitTypes.OctetTime, symbol: "o/m", min: 0 }),
    OctetHour: new UnitDefinition({ type: UnitTypes.OctetTime, symbol: "o/h", min: 0 }),
    OctetDay: new UnitDefinition({ type: UnitTypes.OctetTime, symbol: "o/D", min: 0 }),
    OctetMonth: new UnitDefinition({ type: UnitTypes.OctetTime, symbol: "o/M", min: 0 }),
    OctetYear: new UnitDefinition({ type: UnitTypes.OctetTime, symbol: "o/Y", min: 0 }),

    KiloOctetMicroSeconde: new UnitDefinition({ type: UnitTypes.OctetTime, symbol: "ko/μs", min: 0 }),
    KiloOctetNanoSeconde: new UnitDefinition({ type: UnitTypes.OctetTime, symbol: "ko/ns", min: 0 }),
    KiloOctetMilliSeconde: new UnitDefinition({ type: UnitTypes.OctetTime, symbol: "ko/ms", min: 0 }),
    KiloOctetSeconde: new UnitDefinition({ type: UnitTypes.OctetTime, symbol: "ko/s", min: 0 }),
    KiloOctetMinute: new UnitDefinition({ type: UnitTypes.OctetTime, symbol: "ko/m", min: 0 }),
    KiloOctetHour: new UnitDefinition({ type: UnitTypes.OctetTime, symbol: "ko/h", min: 0 }),
    KiloOctetDay: new UnitDefinition({ type: UnitTypes.OctetTime, symbol: "ko/D", min: 0 }),
    KiloOctetMonth: new UnitDefinition({ type: UnitTypes.OctetTime, symbol: "ko/M", min: 0 }),
    KiloOctetYear: new UnitDefinition({ type: UnitTypes.OctetTime, symbol: "ko/Y", min: 0 }),

    MegaOctetMicroSeconde: new UnitDefinition({ type: UnitTypes.OctetTime, symbol: "Mo/μs", min: 0 }),
    MegaOctetNanoSeconde: new UnitDefinition({ type: UnitTypes.OctetTime, symbol: "Mo/ns", min: 0 }),
    MegaOctetMilliSeconde: new UnitDefinition({ type: UnitTypes.OctetTime, symbol: "Mo/ms", min: 0 }),
    MegaOctetSeconde: new UnitDefinition({ type: UnitTypes.OctetTime, symbol: "Mo/s", min: 0 }),
    MegaOctetMinute: new UnitDefinition({ type: UnitTypes.OctetTime, symbol: "Mo/m", min: 0 }),
    MegaOctetHour: new UnitDefinition({ type: UnitTypes.OctetTime, symbol: "Mo/h", min: 0 }),
    MegaOctetDay: new UnitDefinition({ type: UnitTypes.OctetTime, symbol: "Mo/D", min: 0 }),
    MegaOctetMonth: new UnitDefinition({ type: UnitTypes.OctetTime, symbol: "Mo/M", min: 0 }),
    MegaOctetYear: new UnitDefinition({ type: UnitTypes.OctetTime, symbol: "Mo/Y", min: 0 }),

    GigaOctetMicroSeconde: new UnitDefinition({ type: UnitTypes.OctetTime, symbol: "Go/μs", min: 0 }),
    GigaOctetNanoSeconde: new UnitDefinition({ type: UnitTypes.OctetTime, symbol: "Go/ns", min: 0 }),
    GigaOctetMilliSeconde: new UnitDefinition({ type: UnitTypes.OctetTime, symbol: "Go/ms", min: 0 }),
    GigaOctetSeconde: new UnitDefinition({ type: UnitTypes.OctetTime, symbol: "Go/s", min: 0 }),
    GigaOctetMinute: new UnitDefinition({ type: UnitTypes.OctetTime, symbol: "Go/m", min: 0 }),
    GigaOctetHour: new UnitDefinition({ type: UnitTypes.OctetTime, symbol: "Go/h", min: 0 }),
    GigaOctetDay: new UnitDefinition({ type: UnitTypes.OctetTime, symbol: "Go/D", min: 0 }),
    GigaOctetMonth: new UnitDefinition({ type: UnitTypes.OctetTime, symbol: "Go/M", min: 0 }),
    GigaOctetYear: new UnitDefinition({ type: UnitTypes.OctetTime, symbol: "Go/Y", min: 0 }),

    TeraOctetMicroSeconde: new UnitDefinition({ type: UnitTypes.OctetTime, symbol: "To/μs", min: 0 }),
    TeraOctetNanoSeconde: new UnitDefinition({ type: UnitTypes.OctetTime, symbol: "To/ns", min: 0 }),
    TeraOctetMilliSeconde: new UnitDefinition({ type: UnitTypes.OctetTime, symbol: "To/ms", min: 0 }),
    TeraOctetSeconde: new UnitDefinition({ type: UnitTypes.OctetTime, symbol: "To/s", min: 0 }),
    TeraOctetMinute: new UnitDefinition({ type: UnitTypes.OctetTime, symbol: "To/m", min: 0 }),
    TeraOctetHour: new UnitDefinition({ type: UnitTypes.OctetTime, symbol: "To/h", min: 0 }),
    TeraOctetDay: new UnitDefinition({ type: UnitTypes.OctetTime, symbol: "To/D", min: 0 }),
    TeraOctetMonth: new UnitDefinition({ type: UnitTypes.OctetTime, symbol: "To/M", min: 0 }),
    TeraOctetYear: new UnitDefinition({ type: UnitTypes.OctetTime, symbol: "To/Y", min: 0 }),

    Count: new UnitDefinition({ type: UnitTypes.Count, symbol: "#", min: 0}),

    CountMicroSeconde: new UnitDefinition({ type: UnitTypes.CountTime, symbol: "#/μs" }),
    CountNanoSeconde: new UnitDefinition({ type: UnitTypes.CountTime, symbol: "#/ns" }),
    CountMilliSeconde: new UnitDefinition({ type: UnitTypes.CountTime, symbol: "#/ms" }),
    CountSeconde: new UnitDefinition({ type: UnitTypes.CountTime, symbol: "#/s" }),
    CountMinute: new UnitDefinition({ type: UnitTypes.CountTime, symbol: "#/m" }),
    CountHour: new UnitDefinition({ type: UnitTypes.CountTime, symbol: "#/h" }),
    CountDay: new UnitDefinition({ type: UnitTypes.CountTime, symbol: "#/D" }),
    CountMonth: new UnitDefinition({ type: UnitTypes.CountTime, symbol: "#/M" }),
    CountYear: new UnitDefinition({ type: UnitTypes.CountTime, symbol: "#/Y" }),

    Hertz: new UnitDefinition({ type: UnitTypes.Hertz, symbol: "Hz", min: 0 }),
    KiloHertz: new UnitDefinition({ type: UnitTypes.Hertz, symbol: "kHz", min: 0 }),
    MegaHertz: new UnitDefinition({ type: UnitTypes.Hertz, symbol: "MHz", min: 0 }),
    GigaHertz: new UnitDefinition({ type: UnitTypes.Hertz, symbol: "GHz", min: 0 }),

    Watt: new UnitDefinition({ type: UnitTypes.Watt, symbol: "W", min: 0 }),
    KiloWatt: new UnitDefinition({ type: UnitTypes.Watt, symbol: "kW", min: 0 }),

    WattHour: new UnitDefinition({ type: UnitTypes.WattTime, symbol: "W/h", min: 0 }),
    WattDay: new UnitDefinition({ type: UnitTypes.WattTime, symbol: "W/D", min: 0 }),
    WattMonth: new UnitDefinition({ type: UnitTypes.WattTime, symbol: "W/M", min: 0 }),
    WattYear: new UnitDefinition({ type: UnitTypes.WattTime, symbol: "W/Y", min: 0 }),

    KiloWattHour: new UnitDefinition({ type: UnitTypes.WattTime, symbol: "kW/h", min: 0 }),
    KiloWattDay: new UnitDefinition({ type: UnitTypes.WattTime, symbol: "kW/D", min: 0 }),
    KiloWattMonth: new UnitDefinition({ type: UnitTypes.WattTime, symbol: "kW/M", min: 0 }),
    KiloWattYear: new UnitDefinition({ type: UnitTypes.WattTime, symbol: "kW/Y", min: 0 }),

    Bool: new UnitDefinition({ type: UnitTypes.Boolean, symbol: "bool", min: 0, max: 1 })
};
